export const MOCK_VENDORS = [
  {
    id: 1,
    name: "晴天廚房",
    address: "台北市信義區松仁路 100 號",
    business_hours: "11:00 – 14:00",
    contact_phone: "02-2345-6789",
    contact_email: "sunny@corpmeal.local",
    served_facilities: [{ id: 1, name: "總部大樓" }],
  },
  {
    id: 2,
    name: "山海便當",
    address: "台北市大安區建國南路一段 88 號",
    business_hours: "10:30 – 13:30",
    contact_phone: "02-3456-7890",
    contact_email: "shanhai@corpmeal.local",
    served_facilities: [{ id: 1, name: "總部大樓" }, { id: 2, name: "研發中心" }],
  },
  {
    id: 3,
    name: "好食堂",
    address: "新竹市東區光復路二段 101 號",
    business_hours: "11:30 – 14:30",
    contact_phone: "03-567-8901",
    contact_email: "goodfood@corpmeal.local",
    served_facilities: [{ id: 2, name: "研發中心" }],
  },
];

// The general vendor selections list carries NO employee identity (de-identified):
// employee_id / employee_name are intentionally omitted. Employee identity only
// surfaces on the dedicated by-badge quick-pickup lookup (a separate live call),
// which returns masked_name + badge_code — not modelled in this mock.
export const MOCK_VENDOR_SELECTIONS = [
  {
    id: 1,
    vendor_id: 1,
    item_id: 101,
    item_name: "雞腿飯",
    quantity: 2,
    unit_price_cents: 9000,
    total_price_cents: 18000,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    vendor_id: 1,
    item_id: 102,
    item_name: "排骨飯",
    quantity: 1,
    unit_price_cents: 8500,
    total_price_cents: 8500,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    vendor_id: 1,
    item_id: 101,
    item_name: "雞腿飯",
    quantity: 1,
    unit_price_cents: 9000,
    total_price_cents: 9000,
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    vendor_id: 1,
    item_id: 103,
    item_name: "素食套餐",
    quantity: 1,
    unit_price_cents: 7500,
    total_price_cents: 7500,
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
];

export const MOCK_MENU = {
  1: [
    {
      id: 101,
      vendor_id: 1,
      category_id: 1,
      name: "雞腿飯",
      description: "香煎雞腿配白飯，附醃漬小菜與味噌湯",
      price_cents: 9000,
      available: true,
      daily_quota: 50,
      photo_path: null,
    },
    {
      id: 102,
      vendor_id: 1,
      category_id: 1,
      name: "排骨飯",
      description: "酥炸排骨配滷蛋，附季節蔬菜",
      price_cents: 8500,
      available: true,
      daily_quota: 30,
      photo_path: null,
    },
    {
      id: 103,
      vendor_id: 1,
      category_id: 2,
      name: "素食套餐",
      description: "豆腐、炒時蔬、糙米飯，全素",
      price_cents: 7500,
      available: true,
      daily_quota: null,
      photo_path: null,
    },
    {
      id: 104,
      vendor_id: 1,
      category_id: 1,
      name: "魚排飯",
      description: "今日供應完畢",
      price_cents: 8000,
      available: true,
      daily_quota: 0,
      photo_path: null,
    },
  ],
  2: [
    {
      id: 201,
      vendor_id: 2,
      category_id: 1,
      name: "控肉飯",
      description: "慢燉三層肉，皮Q肉嫩，附半熟滷蛋",
      price_cents: 10000,
      available: true,
      daily_quota: 40,
      photo_path: null,
    },
    {
      id: 202,
      vendor_id: 2,
      category_id: 1,
      name: "鮭魚親子丼",
      description: "鮭魚 + 鮭魚卵，日式高湯蛋汁澆飯",
      price_cents: 13500,
      available: true,
      daily_quota: 20,
      photo_path: null,
    },
    {
      id: 203,
      vendor_id: 2,
      category_id: 2,
      name: "麻辣豆腐煲",
      description: "暫停供應",
      price_cents: 9500,
      available: false,
      daily_quota: 15,
      photo_path: null,
    },
  ],
  3: [
    {
      id: 301,
      vendor_id: 3,
      category_id: 1,
      name: "三杯雞飯",
      description: "台式三杯雞，九層塔香氣十足",
      price_cents: 8500,
      available: true,
      daily_quota: 60,
      photo_path: null,
    },
    {
      id: 302,
      vendor_id: 3,
      category_id: 1,
      name: "蒸蛋豬排飯",
      description: "嫩煎豬排搭配滑嫩蒸蛋",
      price_cents: 9000,
      available: true,
      daily_quota: 35,
      photo_path: null,
    },
  ],
};
